[package]
name = "nim"
version = "0.1.1"
edition = "2024"
description = "nim"
homepage = "https://nim-lang.org/"
repository = "https://github.com/Its-Just-Nans/crates"
keywords = ["nim"]
documentation = "https://docs.rs/nim"
license = "MIT OR Apache-2.0"

[dependencies]
