[package]
name = "nim"
version = "0.1.1"
edition = "2024"
description = "reserved"
homepage = "https://nim-lang.org/"
repository = "https://github.com/Its-Just-Nans/crates"
keywords = ["nim"]
documentation = "https://docs.rs/nim"

[dependencies]
