[package]
name = "bladvak"
version = "0.1.0"
description = "bladvak meant 'pickaxe' in Gobbledegook"
edition = "2021"
license = "MIT"
readme = "README.md"

[[bin]]
name = "bladvak"
path = "src/main.rs"

[dependencies]
