[package]
name = "ruby"
version = "0.1.1"
edition = "2024"
description = "ruby"
homepage = "https://www.ruby-lang.org/"
repository = "https://github.com/Its-Just-Nans/crates"
keywords = ["ruby"]
documentation = "https://docs.rs/ruby"
license = "MIT OR Apache-2.0"

[dependencies]
