[package]
name = "calcifer"
version = "0.1.0"
description = "calcifer"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Its-Just-Nans/crates"

[[bin]]
name = "calcifer"
path = "src/main.rs"

[dependencies]
