[package]
name = "zig"
version = "0.1.1"
edition = "2024"
description = "zig"
homepage = "https://ziglang.org/"
repository = "https://github.com/Its-Just-Nans/crates"
keywords = ["zig"]
documentation = "https://docs.rs/zig"
license = "MIT OR Apache-2.0"

[dependencies]
